CXX=g++
LIBS=-pthread
RM = rm -f
SERVER_EXE = server
CLIENT_EXE = client
SERVER_SRCS = server.cpp 
SERVER_OBJS = $(SERVER_SRCS:.cpp=.o)
CLIENT_SRCS  = client.cpp
CLIENT_OBJS = $(CLIENT_SRCS:.cpp=.o)

build : $(SERVER_EXE) $(CLIENT_EXE)

$(SERVER_EXE):$(SERVER_OBJS)
	$(CXX) $(SERVER_OBJS) -o $(SERVER_EXE) $(LIBS)

$(CLIENT_EXE):$(CLIENT_OBJS)
	$(CXX) $(CLIENT_OBJS) -o $(CLIENT_EXE)

$(SERVER_OBJS):$(SERVER_SRCS)
	$(CXX) -c $(SERVER_SRCS)

$(CLIENT_OBJS):$(CLIENT_SRCS)
	$(CXX) -c $(CLIENT_SRCS)

clean:
	$(RM) $(SERVER_EXE) $(SERVER_OBJS)
	$(RM) $(CLIENT_EXE) $(CLIENT_OBJS)
.PHONY: clean

